[package]
name = "conui"
description = "A devkit for building console applications with a proper user interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
authors.workspace = true

[dependencies]
conui-cell.workspace = true
conui-term.workspace = true
conui-input.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
